name: Deploy to IIS

on:
  push:
    branches:
      - deploy-test

jobs:
  deploy:
    runs-on: self-hosted

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: 20

      - name: Install Dependencies
        run: npm install

      - name: Build Project
        run: npm run build

      - name: Stop IIS
        run: iisreset /stop

      - name: Clear Old Files
        run: Remove-Item -Recurse -Force C:\inetpub\wwwroot\CanteenAPI\*

      - name: Copy New Build
        run: |
          xcopy dist C:\inetpub\wwwroot\CanteenAPI\dist /E /I /Y
          xcopy package.json C:\inetpub\wwwroot\CanteenAPI /Y
          xcopy web.config C:\inetpub\wwwroot\CanteenAPI /Y

      - name: Start IIS
        run: iisreset /start
